config_name: fastmri_varnet,k=6,n=3,max_eig
description: "\"fastmri config, sigma:0.01\""

k_iters: 6
n_layers: 3

epochs: 50

dataset_name: modl_fastmri_dataset
# dataset_name: modl_fastmri_datasetx4

dataset_params:
  dataset_path: 'data/fastmri_dataset.hdf5'
  # dataset_path: 'data/fastmri_tst_dataset.hdf5'

  sigma: 0.01
val_data: true
batch_size: 1

model_name: base_varnet

restore_weights: inter #False, best, inter, final
restore_path: workspace/fastmri_varnet,k=6,n=3,max_eig/checkpoints/  #'workspace/fastmri_varnet,k=5,n=6/checkpoints/'

loss_name: MSE
score_names: ['PSNR', 'SSIM']
optim_name: Adam
optim_params:
  lr: 0.001
gradient_clip: true

# scheduler_name: StepLR
# scheduler_params:
#   step_size: 10
#   gamma: 0.1
